# Generated by Django 5.2 on 2025-08-22 14:54

import params.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the parameter set.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the parameter set.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('params', models.FileField(blank=True, help_text='File containing the parameters in JSON format.', null=True, upload_to=params.models.file_upload_to)),
            ],
            options={
                'verbose_name': 'Parameter Set',
                'verbose_name_plural': 'Parameter Sets',
                'ordering': ['-created_at'],
            },
        ),
    ]
