# Generated by Django 5.2 on 2025-08-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('params', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='organization',
            field=models.ForeignKey(help_text='Organization this parameter set belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='parameter_sets', to='users.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='parameterset',
            unique_together={('name', 'organization')},
        ),
    ]
