# Generated by Django 5.2 on 2026-07-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameterset',
            options={'ordering': ['organization', '-created_at'], 'verbose_name': 'Parameter Set', 'verbose_name_plural': 'Parameter Sets'},
        ),
    ]
