# Generated by Django 5.2 on 2025-08-22 14:54

import opt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('run_directory', models.CharField(blank=True, editable=False, max_length=500)),
                ('input_builder', models.FileField(blank=True, null=True, upload_to=opt.models.file_upload_to)),
                ('is_locked', models.BooleanField(default=False, help_text='Indicates if the run is currently being processed, or done, and cannot be modified.')),
                ('period_start', models.DateTimeField(blank=True, help_text='Start date of the period for which the optimization is run.', null=True)),
                ('period_end', models.DateTimeField(blank=True, help_text='End date of the period for which the optimization is run.', null=True)),
                ('summary_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=opt.models.file_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
