# Generated by Django 5.2 on 2025-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationscenario',
            name='builder_version',
            field=models.CharField(choices=[('v1', 'v1')], default='v1', max_length=3),
        ),
    ]
