# Generated by Django 5.2 on 2025-09-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0003_optimizationscenario_builder_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimizationscenario',
            old_name='input_builder',
            new_name='input_builder',
        ),
    ]
