# Generated by Django 5.2 on 2025-10-07 17:29

import opt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0004_rename_input_file_optimizationscenario_input_builder'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationscenario',
            name='opt_meta_file',
            field=models.FileField(blank=True, help_text='Optional meta file associated with the optimization run.', null=True, upload_to=opt.models.file_upload_to),
        ),
    ]
