# Generated by Django 5.2 on 2025-10-07 21:17

import opt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0005_optimizationscenario_opt_meta_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationscenario',
            name='opt_meta_file',
        ),
        migrations.AddField(
            model_name='optimizationscenario',
            name='run_summary_file',
            field=models.FileField(blank=True, help_text='Optional summary file associated with the optimization run.', null=True, upload_to=opt.models.file_upload_to),
        ),
    ]
