# Generated by Django 5.2 on 2025-10-09 21:25

import opt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0006_remove_optimizationscenario_opt_meta_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationscenario',
            name='user_input',
            field=models.FileField(blank=True, null=True, upload_to=opt.models.file_upload_to),
        ),
        migrations.AlterField(
            model_name='optimizationscenario',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
