# Generated by Django 5.2 on 2025-10-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0007_optimizationscenario_user_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationscenario',
            name='run_directory',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='optimizationscenario',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
