# Generated by Django 5.2 on 2025-10-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0008_alter_optimizationscenario_run_directory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimizationscenario',
            old_name='summary_data',
            new_name='run_summary',
        ),
        migrations.AlterField(
            model_name='optimizationscenario',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('in_queue', 'In Queue'), ('processing', 'Processing'), ('timeout', 'Timeout'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
