# Generated by Django 5.2 on 2025-11-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0009_rename_summary_data_optimizationscenario_run_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimizationscenario',
            name='is_locked',
        ),
    ]
