# Generated by Django 5.2 on 2026-09-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0010_remove_optimizationscenario_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationscenario',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('in_queue', 'In Queue'), ('processing', 'Processing'), ('timeout', 'Timeout'), ('completed', 'Completed'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('response_queue', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('timeout', 'Timeout'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='opt.optimizationscenario')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
    ]
