# Generated by Django 5.2 on 2026-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0011_alter_optimizationscenario_status_optimizationrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationscenario',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
