# Generated by Django 5.2 on 2026-09-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0012_optimizationscenario_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outputfile',
            old_name='run',
            new_name='scenario',
        ),
        migrations.AddField(
            model_name='outputfile',
            name='optimization_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_files', to='opt.optimizationrun'),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('error', 'Error'), ('timeout', 'Timeout'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='optimizationscenario',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('in_queue', 'In Queue'), ('processing', 'Processing'), ('stopping', 'Stopping'), ('timeout', 'Timeout'), ('completed', 'Completed'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=20),
        ),
    ]
