"""
Django settings for django_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Legacy monorepo-era default (sibling repo layout); override via env once
# backend/optimizer exchange data through S3 instead of a shared filesystem
# (see resopt-optimizer's config.py S3_BUCKET / aws.py) — see CLAUDE.md.
OUTPUT_DIR = Path(os.getenv('OPT_OUTPUT_DIR', BASE_DIR / '..' / 'tmp' / 'output')).resolve()
SCENARIOS_DIR = Path(os.getenv('OPT_SCENARIOS_DIR', BASE_DIR / '..' / 'scenarios')).resolve()
PROTECTED_FILES_ROOT = (BASE_DIR / 'protected_files').resolve()
PROJECT_NAME = os.path.basename(BASE_DIR)
print(f"Project name: {PROJECT_NAME}")

ENVIRONMENT = os.getenv('ENVIRONMENT')
if not ENVIRONMENT:
    print("ENVIRONMENT not found in environment variables.")
    exit(1)

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
if not AWS_ACCESS_KEY_ID:
    print("AWS_ACCESS_KEY_ID not found in environment variables.")
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
AWS_QUERYSTRING_AUTH = True  # Optional: False makes S3 URLs public by default
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_DEFAULT_ACL = None  # or 'public-read' (if you want public access)
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",  # Cache files for 1 day
}
AWS_LOCATION = os.getenv("AWS_LOCATION", "") # The folder in your S3 bucket where files will be stored
AWS_PRESIGNED_URL_EXPIRATION = 3600  # 1 hour
OPTIMIZER_RESPONSE_QUEUE_URL = os.getenv("OPTIMIZER_RESPONSE_QUEUE_URL", "")
if not OPTIMIZER_RESPONSE_QUEUE_URL:
    print("OPTIMIZER_RESPONSE_QUEUE_URL not found in environment variables.")
OPTIMIZER_REQUEST_QUEUE_URL = os.getenv("OPTIMIZER_REQUEST_QUEUE_URL", "")
if not OPTIMIZER_REQUEST_QUEUE_URL:
    print("OPTIMIZER_REQUEST_QUEUE_URL not found in environment variables.")
RUN_SUMMARY_FILENAME = "run_summary.json"
STORAGE = os.getenv('STORAGE', 'local')  # 'local' or 's3'

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a7%9zj!51t4bf-*^6rdi6th)f50x2lm=o7%v4g=1k0s7=rp9r@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'storages',
    'rest_framework',

    'opt',
    'users',
    'dashboard',
    'viz',
    'params',
    'logify',
]

MIDDLEWARE = [
    'viz.middleware.MaxUploadSizeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'viz.middleware.MaxUploadSizeMiddleware',
]

ROOT_URLCONF = 'django_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            Path(__file__).resolve().parent / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_backend.context_processors.upload_limits',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
LOCAL_STORAGE = {
    'BACKEND': 'django_backend.storages.OverwriteFileSystemStorage',
}
S3_STORAGE = {
    'BACKEND': 'django_backend.storages.CompressedS3Boto3Storage',
    'OPTIONS': {
        'access_key': AWS_ACCESS_KEY_ID,
        'secret_key': AWS_SECRET_ACCESS_KEY,
        'bucket_name': AWS_STORAGE_BUCKET_NAME,
        'region_name': AWS_S3_REGION_NAME,
        'custom_domain': AWS_CUSTOM_DOMAIN,
        'file_overwrite': True,
        'use_ssl': True,
    }
}
STORAGES = {
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    }
}
if STORAGE == 's3':
    print("Using S3 for storage")
    STORAGES['default'] = S3_STORAGE
    MEDIA_URL = f"https://{AWS_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
else:
    print("Using local storage")
    STORAGES['default'] = LOCAL_STORAGE
    MEDIA_ROOT = BASE_DIR / "media"  # Local file storage path
    MEDIA_URL = '/media/'  # URL to access files from the browser

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_REDIRECT_URL = '/dashboard'
LOGIN_URL = 'users-web:login'
LOGOUT_REDIRECT_URL = '/'

# Changing input file template requires restart
INPUT_BUILDER_TEMPLATE_FILE = BASE_DIR / 'opt/input_builder_template.json'
INPUT_BUILDER_TEMPLATE_CONTENT = INPUT_BUILDER_TEMPLATE_FILE.read_text()
INPUT_BUILDER_FILENAME = 'input_builder.json'
INPUT_FILENAME = 'input.json'
USER_INPUT_FILENAME = 'user_input.json'
OUTPUT_FILENAME = 'output.json'

DEFAULT_PARAMETER_SET_FILE = BASE_DIR / 'default_parameters.json'
DEFAULT_PARAMETER_SET_CONTENT = DEFAULT_PARAMETER_SET_FILE.read_text()

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOG_DIR = BASE_DIR / 'log'
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Keeps existing loggers like 'django'
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'default',  # Apply the default formatter here
        },
    },
    'loggers': {
        'preprocess': {
            'handlers': ['console'],
            'level': 'DEBUG',  # Or 'DEBUG' if you want more
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',  # To avoid overly verbose logs from other modules
    },
    'formatters': {
        'default': {
            'format': '%(asctime)s - %(levelname)s - %(message)s',  # Format for timestamp, level, and message
            'datefmt': '%Y-%m-%d %H:%M:%S',  # Specify date format for the timestamp
        },
    },
}
